### ISSUE TITLE
Chandna - GitHub Flow steps

### ISSUE THREAD

**Issue by cphalaswal** [githubschool/refactored-fiesta#8]
:sparkles: :camel: :boom:

- [x] Branch Off of master
- [x] Create commits on new branch
- [x] open a PR on GitHub
- [x] Code review + collaboration
- [x] Merge on approval

-Fun Starts-

**Comment by apanchanathan** [comment]
```SQL
SELECT * FROM dbm

**Comment by cphalaswal** [comment]
Branch has been created ...yay..

**Comment by cphalaswal** [comment]
Done with everything
